### ISSUE TITLE
Exit Entire app

### ISSUE THREAD

**Issue by Barathwaja** [srbcheema1/ExeploreGame#15]
Couldn't exit the application. Using Eclipse IDE , Ubuntu OS.

**Comment by Raman1121** [comment]
I would like to work on this.

**Comment by srbcheema1** [comment]
@Barathwaja 
the way to exit app is to press Ctrl+C
the game was selected for a gaming compition 
so i added this feature that one cannot close the application in between the game time .
so that organisers may come and note the score of player before he exit the game

**Comment by srbcheema1** [comment]
@Barathwaja 
@Raman1121 
i would love to see contributions from your side to this project 
also if you found this game interesting please do give a  STAR

**Comment by caioz7** [comment]
We can change the "_DO_NOTHING_ON_CLOSE_" to "_EXIT_ON_CLOSE_"
Or, we can add a exit button.

**Comment by srbcheema1** [comment]
@caioz7 
that was kept intentionally
