### ISSUE TITLE
Add database support to the game 

### ISSUE THREAD

**Issue by srbcheema1** [srbcheema1/ExeploreGame#4]
this game is a java based game .
at end of game player is given a score .
i want to store the score in database so that from next time we can check best score

**Comment by Akatsuki06** [comment]
@srbcheema1 I think scores can be stored in a file as well. Using database will be redundant.

**Comment by srbcheema1** [comment]
yes this may also be perfect @Akatsuki06 
you may go for it if you would like to contribute :)

**Comment by Akatsuki06** [comment]
I will make a utility class functionality for allowing to save score. ok

**Comment by srbcheema1** [comment]
that will be great @Akatsuki06 
also dont forget to give a STAR to this repository if you found it interesting

**Comment by Akatsuki06** [comment]
Use **Score.getScore(fileName)** to get the score
       and **Score.saveScore(score,fileName)** to save,
       Note:the fileName can be that specific level name  with a dir path as there will be different levels in the game
       Also the score are being saved in binary so that user couldnt modify them.

**Comment by srbcheema1** [comment]
thanks @Akatsuki06 
got that 
i will surely work on that :smile:
